[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gcoordinator"
version = "0.0.1"
authors = [
  { name="Tomohiro TANIGUCHI", email="tomohiron907@gmail.com" },
]
description = "a package for generate G-code for 3D Printer"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"